kind: secret
name: sonar_host
---
kind: secret
name: sonar_project_token
---

kind: pipeline
type: docker
name: Analysis

steps:
  - name: Install node modules
    image: node:10.16.3
    commands:
      - yarn install

  - name: Test
    image: node:10.16.3
    commands:
      - yarn test

  - name: Sonar Scanner
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_token:
        from_secret: sonar_project_token
      sonar_host:
        from_secret:
          sonar_url
      ver: 1.0

trigger:
    branch:
      - main
